### ISSUE TITLE
Remotely activating node is not successful

### ISSUE THREAD

**Issue by gdiscord** [project-liberty/wallet#39]
This issue tracker is only for technical issues related to Liberty Coin.
General Liberty questions and/or support requests and are best directed to the [Liberty Discord](https://discord.liberty-coin.com).

### Describe the issue
Remotely activating the node is not successful

#### If so, please list the steps to reproduce below:
1. download 5.1.1 wallet to vps and run it to fully sync.
2. download 5.1.1 wallet to desktop and run it to fully sync.
3. activate the node remotely from the desktop wallet

### Expected behavior
vps node should show that it was started successfully
### Actual behavior
not a capable masternode: hot node, waiting for remote activation.
  "version": 5010100,
  "protocolversion": 71027,
  "walletversion": 61000,

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Liberty Coin are you using?

  "version": 5010100,
  "protocolversion": 71027,
  "walletversion": 61000,

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by binarysculptor** [comment]
What version of Ubuntu is on the vps?
What version of Windows are you using?
Are you using the x86 or x64 bins on the Windows machine?
Please provide the debug.log files for the vps and the Windows machine
after adding debug=1 to each config file and getting the issue to manifest.

**Comment by gdiscord** [comment]
this turned out to be an isolated case. The activation eventually worked. Perhaps caching caused the issue. 

Closing case.
