### ISSUE TITLE
3 Transactions that has just dissapeared

### ISSUE THREAD

**Issue by JohanTh** [project-liberty/wallet#40]
### Describe the issue
3 transactions has been made, coins has been lost and coins has dissapeared.

### Can you reliably reproduce the issue?
1. Send xlib coins from the wallet

### Expected behavior
Sent coin should reach destination address

### Actual behavior
Coins dissapear and the transaction does not exist on the explorer

### Screenshots.
![capture](https://user-images.githubusercontent.com/4187434/51438748-5e188d80-1cb0-11e9-92c3-e5c4553d5206.PNG)

### What version of Liberty Coin are you using?
I sent the coins using the wallet 5.0.58.0-31a8cea

### Machine specs:
- OS: Windows
- CPU: Intel i7 5820K 3,3 GHz 15MB
- RAM: Crucial 16GB (4x4GB) DDR4 2133Mhz + Corsair 16GB (4x4GB) DDR4 2666MHz CL15 VENGEANCE (32GB total)
- Disk size: 3TB WD Red PRO 7200rpm 64MB
- Disk Type (HD/SDD): HD

The address I've sent these conins to is CryptoBriges `XadqrW8x4oacLG5cb5UHAHwvvrLjp7PSHu`. You can see that my 18k transaction has gone trough but the three lates transactions on the screenshot has not on this account.

The transaction details are:

```
Status: 7120 confirmations
Date: 2019-01-15 12:52
To: CryptoBridge XadqrW8x4oacLG5cb5UHAHwvvrLjp7PSHu
Debit: -20 600.00000000 XLIB
Net amount: -20 600.00071957 XLIB
Transaction ID: b7b56d63e293e640cb3682b64c27934787b525238e4e24585357d37afed1be54
Output index: 0
```

```
Status: 4011 confirmations
Date: 2019-01-16 14:37
To: CryptoBridge XadqrW8x4oacLG5cb5UHAHwvvrLjp7PSHu
Debit: -43 000.00000000 XLIB
Net amount: -43 000.00124832 XLIB
Transaction ID: a609a93e3afd51e5fbfce682bdd7d3dd174f75484fa5964d4ce2d3e31622be15
Output index: 0
```

```
Status: 3795 confirmations
Date: 2019-01-17 20:46
To: CryptoBridge XadqrW8x4oacLG5cb5UHAHwvvrLjp7PSHu
Debit: -5376.00000000 XLIB
Net amount: -5376.00016801 XLIB
Transaction ID: 979a4916e46c3674566b2e1e264f90cc7ee3fd1a0fc031ed5245a44fb20b10cd
Output index: 0
```

**Comment by JohanTh** [comment]
I just tried sending 100 coins to the same CryptoBridge address from wallet version `v5.1.1.0-e13666e` and the transaction does not exist.

```
Status: 7 confirmations
Date: 2019-01-20 12:50
To: CryptoBridge XadqrW8x4oacLG5cb5UHAHwvvrLjp7PSHu
Debit: -100.00000000 XLIB
Net amount: -100.00002260 XLIB
Transaction ID: 418cd38b1e37b24bee5ab1ad5dc72b89815cb33fd5d8a680674561c3b846f1e7
Output index: 0
```

![capture](https://user-images.githubusercontent.com/4187434/51439055-27914180-1cb5-11e9-893c-c1099a421c90.PNG)

Making a payment to my own address does not seem to work either.

All my receiving addresses are:
```
XCqgJV2Su8wqGtiftxh1ZXYkBjPoCQVJp8
XRDZAACvCjJ27vQx2WWGXoyTQeRwUQQ6b8
XJgZYHd2rA7tdBem1FqfNNd4nKKQrXkUmu
XTuyc4fLqARNbsgtMSFumFYSmiXvbfe2uy
XGLTtaj2fjjr6cAKZnKa42VNrVnJfSR1iq
XCLTvHy2hEcc9aB4RLjheV9N4QSxmkkzz4
XWregHJGBh8GfjXuMLLNV9BEsSw2qeQY2E
XTk95KJ4pqDZX83cJQMzc6h9pEcgDXyLCT
```

**Comment by JohanTh** [comment]
Debug log: https://gist.github.com/JohanTh/70fdc73f48f4ae56b20ef76d9c009700

**Comment by binarysculptor** [comment]
You need to resync you wallet.

**Comment by JohanTh** [comment]
Did it and now all coins are stuck as immature, for more than 24h now.

**Comment by binarysculptor** [comment]
Please provide your debug.log

**Comment by JohanTh** [comment]
https://gist.github.com/JohanTh/c912c214de2144f5d3181c651533f63f

**Comment by binarysculptor** [comment]
You will need to add debug=1 to your wallet config, delete your debug.log
file (with the wallet off) and then restart it.

Afterward, please open the wallet repair screen and click on zapwallettx=2.
Your wallet will restart and rescan the blockchain for transactions that
are invalid.

Please make 100% certain that your wallet is on the same block as our
explorers.

Email me the updated debug.log file to martin@liberty-coin.com
